openapi: 3.0.1
info:
  title: Cryptocurrency Market APIs
  version: 1.0.0
  description: >-
    A basic API for working with the swagger tools to support routes in the
    server.
paths:
  /fetchallwatchlists:
    summary: Get all watchlist
    description: This path will fetch the list of all watchlist from the database.
    get:
      summary: Get all watchlists from the database.
      description: >-
        This path will retrieve the list of all watchlists saved in the
        database.
      operationId: get_watchlist
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                watchlist sample:
                  value: >-
                    {"_id":{"$oid":"623ece91fc9e0d1da809bf83"},"user":{"$oid":"623ece0efc9e0d1da809bf80"},"coinid":"bitcoin","__v":0}
      tags:
        - watchlist
  /addwatchlist:
    summary: Add a new watchlist
    description: This path will add a new watchlist to the database.
    post:
      summary: Add a new watchlist
      description: This route will add a new watchlist to the database.
      operationId: post_watchlist
      requestBody:
        description: A new watchlist object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/watchlist'
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                watchlist sample:
                  value: >-
                    {"_id":{"$oid":"623ece91fc9e0d1da809bf83"},"user":{"$oid":"623ece0efc9e0d1da809bf80"},"coinid":"bitcoin","__v":0}
      tags:
        - watchlist
  /updatewatchlist/:id:
    summary: Update a watchlist
    description: This path will be used to update an existing watchlist in the database.
    put:
      summary: Update a watchlist
      description: This route will update an existing watchlist from the database.,
      operationId: put_watchlist
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                watchlist sample:
                  value: >-
                    {"_id":{"$oid":"623ece91fc9e0d1da809bf83"},"user":{"$oid":"623ece0efc9e0d1da809bf80"},"coinid":"bitcoin","__v":0}
      tags:
        - watchlist
  /deletewatchlist/:id:
    summary: Delete a watchlist
    description: This path will be used to delete an existing watchlist in the database.
    delete:
      summary: Delete a watchlist
      description: This path will delete an existing watchlist from the database.
      operationId: delete_watchlist
      responses:
        default:
          description: Default error sample response
          content:
            text/plain; charset=utf-8:
              examples:
                watchlist:
                  value: watchlist deleted!
      tags:
        - watchlist
components:
  schemas:
    watchlist:
      type: object
      properties:
        id:
          type: string
        coinid:
          type: string
      xml:
        name: watchlist
